### ISSUE TITLE
HA Setup

### ISSUE THREAD

**Issue by maaft** [siderolabs/discovery-service#44]
Can this discovery service be hosted in a HA setup?

I fear that this could be a single point of failure in our infrastructure.

**Comment by smira** [comment]
This service is in-memory, and it is designed to survive crashes. 

Talos client is implemented in such a way that it will automatically refresh data about itself whenever it loses connection to the discovery service. So even if the service crashes, the data will be re-filled back within couple of minutes.

Talos doesn't have hard dependency on discovery service, i.e. it will keep working even if the discovery service is down.
