### ISSUE TITLE
Add support for `arm64`

### ISSUE THREAD

**Issue by twelho** [siderolabs/discovery-service#52]
Currently, the build system seems to only be able to build `amd64` binaries and container images. I attempted a quick and dirty `sed -i 's/amd64/arm64/g' Makefile Dockerfile`, which produced a working binary and container image without issues, so multiarch support should be relatively simple to add. However, both the `Makefile` and `Dockerfile` mention that they're autogenerated with with `kres`, and I'm unsure how to to add multiarch support with it.

**Comment by frezbo** [comment]
It's easy as adding similar to the ones here in this kres file https://github.com/siderolabs/bldr/blob/main/.kres.yaml and running `make rekres`

**Comment by twelho** [comment]
Thanks for the hint! I've now implemented the required changes in https://github.com/siderolabs/discovery-service/pull/53.
